Tag.create!(name: "株式投資")
Tag.create!(name: "決算")
Tag.create!(name: "IPO")
Tag.create!(name: "仮想通貨")
Tag.create!(name: "テクニカル")
Tag.create!(name: "ファンダメンタル")
Tag.create!(name: "イベントドリブン")
Tag.create!(name: "システムトレード")
Tag.create!(name: "金融工学")
Tag.create!(name: "プログラム")

User.create!(name: "test1", email: "test1@gmail.com", password: "111111")
User.create!(name: "test2", email: "test2@gmail.com", password: "111111")
User.create!(name: "test3", email: "test3@gmail.com", password: "111111")
User.create!(name: "test4", email: "test4@gmail.com", password: "111111")
User.create!(name: "test5", email: "test5@gmail.com", password: "111111")