Tag.create!(name: "株式投資")
Tag.create!(name: "決算")
Tag.create!(name: "IPO")
Tag.create!(name: "仮想通貨")
Tag.create!(name: "テクニカル")
Tag.create!(name: "ファンダメンタル")
Tag.create!(name: "イベントドリブン")
Tag.create!(name: "システムトレード")
Tag.create!(name: "金融工学")
Tag.create!(name: "プログラム")

User.create!(name: "test1", email: "test1@gmail.com", password: "111111")
User.create!(name: "test2", email: "test2@gmail.com", password: "111111")
User.create!(name: "test3", email: "test3@gmail.com", password: "111111")
User.create!(name: "test4", email: "test4@gmail.com", password: "111111")
User.create!(name: "test5", email: "test5@gmail.com", password: "111111")

Article.create!(taile: "test1", content: "content1", impressions_count: 0, user_id: 1)
Article.create!(taile: "test2", content: "content2", impressions_count: 0, user_id: 2)
Article.create!(taile: "test3", content: "content3", impressions_count: 0, user_id: 3)
Article.create!(taile: "test4", content: "content4", impressions_count: 0, user_id: 4)
Article.create!(taile: "test5", content: "content5", impressions_count: 0, user_id: 5)

Comment.create!(article_id: 1, content: "コメントしました")
Comment.create!(article_id: 2, content: "コメントしました")
Comment.create!(article_id: 3, content: "コメントしました")
Comment.create!(article_id: 4, content: "コメントしました")
Comment.create!(article_id: 5, content: "コメントしました")

Like.create!(user_id: 5, article_id: 1)
Like.create!(user_id: 4, article_id: 2)
Like.create!(user_id: 3, article_id: 3)
Like.create!(user_id: 2, article_id: 4)
Like.create!(user_id: 1, article_id: 5)

Stock.create!(user_id: 5, article_id: 1)
Stock.create!(user_id: 4, article_id: 2)
Stock.create!(user_id: 3, article_id: 3)
Stock.create!(user_id: 2, article_id: 4)
Stock.create!(user_id: 1, article_id: 5)

Tagging.create!(tag_id: 5, article_id: 1)
Tagging.create!(tag_id: 4, article_id: 2)
Tagging.create!(tag_id: 3, article_id: 3)
Tagging.create!(tag_id: 2, article_id: 4)
Tagging.create!(tag_id: 1, article_id: 5)

